name: build
on:
  push:
    branches:
      - develop
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch test
        run: |
          npm test --browsers ChromeHeadless
        env:
            CI: true
        
